//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dauti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProdID { get; set; }
        public string PrName { get; set; }
        public string PrBarCode { get; set; }
        public string PrCode { get; set; }
        public string PrImage { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
